### ISSUE TITLE
Submitting Assignment #2

### ISSUE THREAD

**Issue by wilbertsmdo** [VIS-2129-F2020/wilbert_smdo-vis#1]
(Previously submitted via email, just now submitting via Github).

HTML
https://github.com/VIS-2129-F2020/wilbert_smdo-vis/blob/master/Creative_Assignment_2b.html

**Comment by bauranov** [comment]
Good work! Here are some comments:
- Suppress messages and warnings with {r, message=FALSE, warning=FALSE}.
- Consider adding names of countries to the map.
- Try exploring different color palettes, other than Viridis.
